# Generated by Django 2.2.4 on 2020-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Awosome Blogging Page!', max_length=50),
        ),
    ]
